### ISSUE TITLE
Changed tweepy API leads to issues when updating status

### ISSUE THREAD

**Issue by TomLottermann** [django-blog-zinnia/zinnia-twitter#1]
Hi!

I was trying to set up the twitter plugin, but ran into an exception. This was actually cause by the way you call the tweepy api at https://github.com/django-blog-zinnia/zinnia-twitter/blob/develop/zinnia_twitter/admin.py#L45

```
api.update_status(message)
```

It seems like tweepy have changed the API slightly:
https://github.com/tweepy/tweepy/blob/master/tweepy/api.py#L178

This is very simple to fix.

**Comment by Fantomas42** [comment]
Thanks for your good job !
