### ISSUE TITLE
Visitors could share articles on Twitter too ?

### ISSUE THREAD

**Issue by tonioo** [django-blog-zinnia/zinnia-twitter#5]
Hi,
I'm looking for a plugin to allow visitors to share blog articles on Twitter. I already use this plugin and I'm wondering if that's something you could add ?
Or maybe something similar already exists ?

Thank you for your answer.

**Comment by Fantomas42** [comment]
Implementing this functionality is done at the template level and it's really specific.

So I do not want to support this feature in this package.

Just add their script, configure it, and you are done.
